## 데이터 인코딩
#### 1. 원-핫 인코딩(One-Hot encoding)

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


#### 2. Get_Dummies

In [4]:
import pandas as pd
pd.get_dummies(items)

TV  냉장고  믹서  선풍기  전자렌지  컴퓨터
0   1    0   0    0     0    0
1   0    1   0    0     0    0
2   0    0   0    0     1    0
3   0    0   0    0     0    1
4   0    0   0    1     0    0
5   0    0   0    1     0    0
6   0    0   1    0     0    0
7   0    0   1    0     0    0

##### ** 원핫 인코딩을 수행하는 과정으로는 get_dummies()와  sklearn라이브러리에서 제공하는 OneHotEncoder() 함수가 있다.
##### ** 이 두 함수는 수행되는 메커니즘이 유사하나, OneHotEncoder() 함수는 범주형 변수 외의 연속형 변수까지 모두 인코딩을 수행하는 특징을 가지고 있으며 모델 객체와 모델을 학습하는 코드를 추가로 작성해야 한다.
##### ** 따라서 단순히 함수 호출만으로 범주형 데이털르 자동으로 골라서 인코딩하는 get_dummies() 함수의 사용이 더 유용할 것으로 보인다